#!/usr/bin/env python3
"""Generate a curated FastMCP server from Semaphore's OpenAPI (Swagger 2.0) spec.

Why a generator and not a generic bridge:
  * Semaphore's spec ships EMPTY operationIds -> a naive bridge emits unusable
    tool names. We synthesise clean names here.
  * The raw spec is 127 operations, 38 destructive. We expose a curated ~13.
  * Annotations (readOnlyHint / destructiveHint) are derived from the HTTP verb
    and the tool's declared `kind`, so hints are honest and automatic.

Run:  python generate.py  ->  writes server.py
"""
import re
import yaml

SPEC = "api-docs.yml"
OUT = "server.py"

# --- Curated allowlist: (tool_name, METHOD, path_template, kind) -------------
# kind drives annotations + whether it lands in deny/ask/allow buckets.
#   "read"  -> readOnlyHint=True                     (silent-allow candidate)
#   "run"   -> state-changing, NOT destructive       (ask candidate)
# Destructive ops (DELETE/PUT) are deliberately ABSENT: they are never emitted.
ALLOWLIST = [
    ("list_projects",    "GET",  "/projects",                                     "read"),
    ("get_project",      "GET",  "/project/{project_id}/",                        "read"),
    ("list_templates",   "GET",  "/project/{project_id}/templates",               "read"),
    ("get_template",     "GET",  "/project/{project_id}/templates/{template_id}", "read"),
    ("list_tasks",       "GET",  "/project/{project_id}/tasks",                   "read"),
    ("get_last_tasks",   "GET",  "/project/{project_id}/tasks/last",              "read"),
    ("get_task",         "GET",  "/project/{project_id}/tasks/{task_id}",         "read"),
    ("get_task_output",  "GET",  "/project/{project_id}/tasks/{task_id}/output",  "read"),
    ("list_inventory",   "GET",  "/project/{project_id}/inventory",               "read"),
    ("get_inventory",    "GET",  "/project/{project_id}/inventory/{inventory_id}","read"),
    ("list_environment", "GET",  "/project/{project_id}/environment",             "read"),
    ("run_task",         "POST", "/project/{project_id}/tasks",                   "run"),
    ("stop_task",        "POST", "/project/{project_id}/tasks/{task_id}/stop",    "run"),
]

HEADER = '''#!/usr/bin/env python3
"""Semaphore MCP server (POC) - GENERATED by generate.py. Do not edit by hand.

Env:
  SEMAPHORE_URL    e.g. https://semaphore.example.com
  SEMAPHORE_TOKEN  bearer API token (scope this to a read+run RBAC user)
"""
import os
import sys
import json
import asyncio
import httpx
from mcp.server.fastmcp import FastMCP
from mcp.types import ToolAnnotations

BASE = os.environ.get("SEMAPHORE_URL", "").rstrip("/")
TOKEN = os.environ.get("SEMAPHORE_TOKEN", "")

mcp = FastMCP("semaphore")


async def _request(method, path, query=None, body=None):
    if not BASE or not TOKEN:
        return {"error": "SEMAPHORE_URL / SEMAPHORE_TOKEN not set"}
    url = BASE + "/api" + path
    headers = {"Authorization": f"Bearer {TOKEN}", "Accept": "application/json"}
    async with httpx.AsyncClient(timeout=30) as c:
        r = await c.request(method, url, headers=headers, params=query, json=body)
        r.raise_for_status()
        ct = r.headers.get("content-type", "")
        return r.json() if "json" in ct else r.text
'''


def path_params(path):
    return re.findall(r"{(\w+)}", path)


def emit_tool(name, method, path, kind):
    pp = path_params(path)
    read_only = kind == "read"
    # annotations derived from verb + kind (the honest-hints part of the POC)
    ann = (f'ToolAnnotations(title={name!r}, readOnlyHint={read_only}, '
           f'destructiveHint=False, idempotentHint={read_only}, openWorldHint=False)')

    args = [f"{p}: int" for p in pp]
    if kind == "read" and name.startswith("list_"):
        args += ['sort: str = "name"', 'order: str = "asc"']
    if name == "run_task":
        args += ["template_id: int", 'environment: str = ""', 'limit: str = ""']

    sig = ", ".join(args)
    # build the runtime f-string path with params substituted
    runtime_path = path
    for p in pp:
        runtime_path = runtime_path.replace("{" + p + "}", "{" + p + "}")

    body_lines = []
    query_expr = "None"
    body_expr = "None"
    if kind == "read" and name.startswith("list_"):
        query_expr = '{"sort": sort, "order": order}'
    if name == "run_task":
        body_lines.append('    body = {"template_id": template_id, "project_id": project_id, '
                          '"environment": environment, "limit": limit}')
        body_expr = "body"

    doc = f"{method} {path}"
    lines = [
        f"@mcp.tool(annotations={ann})",
        f"async def {name}({sig}) -> str:",
        f'    """{doc}"""',
    ]
    lines += body_lines
    lines.append(f'    res = await _request("{method}", f"{runtime_path}", '
                 f'query={query_expr}, body={body_expr})')
    lines.append("    return json.dumps(res, indent=2, default=str)")
    return "\n".join(lines)


def main():
    spec = yaml.safe_load(open(SPEC))
    known = {(m.upper(), p) for p, item in spec["paths"].items()
             for m in item if m in ("get", "post", "put", "delete")}
    out = [HEADER]
    emitted = 0
    for name, method, path, kind in ALLOWLIST:
        assert (method, path) in known, f"{method} {path} not in spec!"
        out.append("\n\n" + emit_tool(name, method, path, kind))
        emitted += 1

    footer = '''


def _list():
    tools = asyncio.run(mcp.list_tools())
    for t in tools:
        a = t.annotations
        ro = getattr(a, "readOnlyHint", None) if a else None
        print(f"{t.name:18} readOnly={ro}  desc={t.description}")
    print(f"\\n{len(tools)} tools exposed (spec has 127 operations; 38 destructive omitted)")


if __name__ == "__main__":
    if "--list" in sys.argv:
        _list()
    else:
        mcp.run()
'''
    out.append(footer)
    open(OUT, "w").write("".join(out))
    print(f"wrote {OUT}: {emitted} curated tools from {len(known)} spec operations")


if __name__ == "__main__":
    main()
