#!/usr/bin/env python3
"""Semaphore MCP server (POC) - GENERATED by generate.py. Do not edit by hand.

Env:
  SEMAPHORE_URL    e.g. https://semaphore.example.com
  SEMAPHORE_TOKEN  bearer API token (scope this to a read+run RBAC user)
"""
import os
import sys
import json
import asyncio
import httpx
from mcp.server.fastmcp import FastMCP
from mcp.types import ToolAnnotations

BASE = os.environ.get("SEMAPHORE_URL", "").rstrip("/")
TOKEN = os.environ.get("SEMAPHORE_TOKEN", "")

mcp = FastMCP("semaphore")


async def _request(method, path, query=None, body=None):
    if not BASE or not TOKEN:
        return {"error": "SEMAPHORE_URL / SEMAPHORE_TOKEN not set"}
    url = BASE + "/api" + path
    headers = {"Authorization": f"Bearer {TOKEN}", "Accept": "application/json"}
    async with httpx.AsyncClient(timeout=30) as c:
        r = await c.request(method, url, headers=headers, params=query, json=body)
        r.raise_for_status()
        ct = r.headers.get("content-type", "")
        return r.json() if "json" in ct else r.text


@mcp.tool(annotations=ToolAnnotations(title='list_projects', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def list_projects(sort: str = "name", order: str = "asc") -> str:
    """GET /projects"""
    res = await _request("GET", f"/projects", query={"sort": sort, "order": order}, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_project', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_project(project_id: int) -> str:
    """GET /project/{project_id}/"""
    res = await _request("GET", f"/project/{project_id}/", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='list_templates', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def list_templates(project_id: int, sort: str = "name", order: str = "asc") -> str:
    """GET /project/{project_id}/templates"""
    res = await _request("GET", f"/project/{project_id}/templates", query={"sort": sort, "order": order}, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_template', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_template(project_id: int, template_id: int) -> str:
    """GET /project/{project_id}/templates/{template_id}"""
    res = await _request("GET", f"/project/{project_id}/templates/{template_id}", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='list_tasks', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def list_tasks(project_id: int, sort: str = "name", order: str = "asc") -> str:
    """GET /project/{project_id}/tasks"""
    res = await _request("GET", f"/project/{project_id}/tasks", query={"sort": sort, "order": order}, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_last_tasks', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_last_tasks(project_id: int) -> str:
    """GET /project/{project_id}/tasks/last"""
    res = await _request("GET", f"/project/{project_id}/tasks/last", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_task', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_task(project_id: int, task_id: int) -> str:
    """GET /project/{project_id}/tasks/{task_id}"""
    res = await _request("GET", f"/project/{project_id}/tasks/{task_id}", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_task_output', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_task_output(project_id: int, task_id: int) -> str:
    """GET /project/{project_id}/tasks/{task_id}/output"""
    res = await _request("GET", f"/project/{project_id}/tasks/{task_id}/output", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='list_inventory', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def list_inventory(project_id: int, sort: str = "name", order: str = "asc") -> str:
    """GET /project/{project_id}/inventory"""
    res = await _request("GET", f"/project/{project_id}/inventory", query={"sort": sort, "order": order}, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_inventory', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_inventory(project_id: int, inventory_id: int) -> str:
    """GET /project/{project_id}/inventory/{inventory_id}"""
    res = await _request("GET", f"/project/{project_id}/inventory/{inventory_id}", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='list_environment', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def list_environment(project_id: int, sort: str = "name", order: str = "asc") -> str:
    """GET /project/{project_id}/environment"""
    res = await _request("GET", f"/project/{project_id}/environment", query={"sort": sort, "order": order}, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='run_task', readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=False))
async def run_task(project_id: int, template_id: int, environment: str = "", limit: str = "") -> str:
    """POST /project/{project_id}/tasks"""
    body = {"template_id": template_id, "project_id": project_id, "environment": environment, "limit": limit}
    res = await _request("POST", f"/project/{project_id}/tasks", query=None, body=body)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='stop_task', readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=False))
async def stop_task(project_id: int, task_id: int) -> str:
    """POST /project/{project_id}/tasks/{task_id}/stop"""
    res = await _request("POST", f"/project/{project_id}/tasks/{task_id}/stop", query=None, body=None)
    return json.dumps(res, indent=2, default=str)


def _list():
    tools = asyncio.run(mcp.list_tools())
    for t in tools:
        a = t.annotations
        ro = getattr(a, "readOnlyHint", None) if a else None
        print(f"{t.name:18} readOnly={ro}  desc={t.description}")
    print(f"\n{len(tools)} tools exposed (spec has 127 operations; 38 destructive omitted)")


if __name__ == "__main__":
    if "--list" in sys.argv:
        _list()
    else:
        mcp.run()
