#!/usr/bin/env python3
"""Semaphore MCP server (POC) - GENERATED by generate.py. Do not edit by hand.

Three tiers, guardrailed — NOT read-only:
  read   -> safe to auto-allow
  write  -> create/update/run; state-changing but non-destructive
  delete -> destructive; refuses unless called with confirm=True

Env:
  SEMAPHORE_URL    e.g. https://semaphore.example.com
  SEMAPHORE_TOKEN  bearer API token (scope RBAC to match the tier you allow)
"""
import os
import sys
import json
import asyncio
from typing import Optional
import httpx
from mcp.server.fastmcp import FastMCP
from mcp.types import ToolAnnotations

BASE = os.environ.get("SEMAPHORE_URL", "").rstrip("/")
TOKEN = os.environ.get("SEMAPHORE_TOKEN", "")

mcp = FastMCP("semaphore")


async def _request(method, path, query=None, body=None):
    if not BASE or not TOKEN:
        return {"error": "SEMAPHORE_URL / SEMAPHORE_TOKEN not set"}
    url = BASE + "/api" + path
    headers = {"Authorization": f"Bearer {TOKEN}", "Accept": "application/json"}
    async with httpx.AsyncClient(timeout=30) as c:
        r = await c.request(method, url, headers=headers, params=query, json=body)
        r.raise_for_status()
        ct = r.headers.get("content-type", "")
        return r.json() if "json" in ct else r.text


@mcp.tool(annotations=ToolAnnotations(title='list_projects', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def list_projects(sort: str = "name", order: str = "asc") -> str:
    """GET /projects"""
    res = await _request("GET", f"/projects", query={"sort": sort, "order": order}, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_project', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_project(project_id: int) -> str:
    """GET /project/{project_id}/"""
    res = await _request("GET", f"/project/{project_id}/", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='list_templates', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def list_templates(project_id: int, sort: str = "name", order: str = "asc") -> str:
    """GET /project/{project_id}/templates"""
    res = await _request("GET", f"/project/{project_id}/templates", query={"sort": sort, "order": order}, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_template', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_template(project_id: int, template_id: int) -> str:
    """GET /project/{project_id}/templates/{template_id}"""
    res = await _request("GET", f"/project/{project_id}/templates/{template_id}", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='list_tasks', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def list_tasks(project_id: int, sort: str = "name", order: str = "asc") -> str:
    """GET /project/{project_id}/tasks"""
    res = await _request("GET", f"/project/{project_id}/tasks", query={"sort": sort, "order": order}, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_last_tasks', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_last_tasks(project_id: int) -> str:
    """GET /project/{project_id}/tasks/last"""
    res = await _request("GET", f"/project/{project_id}/tasks/last", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_task', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_task(project_id: int, task_id: int) -> str:
    """GET /project/{project_id}/tasks/{task_id}"""
    res = await _request("GET", f"/project/{project_id}/tasks/{task_id}", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_task_output', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_task_output(project_id: int, task_id: int) -> str:
    """GET /project/{project_id}/tasks/{task_id}/output"""
    res = await _request("GET", f"/project/{project_id}/tasks/{task_id}/output", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='list_inventory', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def list_inventory(project_id: int, sort: str = "name", order: str = "asc") -> str:
    """GET /project/{project_id}/inventory"""
    res = await _request("GET", f"/project/{project_id}/inventory", query={"sort": sort, "order": order}, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='get_inventory', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def get_inventory(project_id: int, inventory_id: int) -> str:
    """GET /project/{project_id}/inventory/{inventory_id}"""
    res = await _request("GET", f"/project/{project_id}/inventory/{inventory_id}", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='list_environment', readOnlyHint=True, destructiveHint=False, idempotentHint=True, openWorldHint=False))
async def list_environment(project_id: int, sort: str = "name", order: str = "asc") -> str:
    """GET /project/{project_id}/environment"""
    res = await _request("GET", f"/project/{project_id}/environment", query={"sort": sort, "order": order}, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='run_task', readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=False))
async def run_task(project_id: int, template_id: int, environment: str = "", limit: str = "") -> str:
    """POST /project/{project_id}/tasks"""
    body = {"project_id": project_id, "template_id": template_id, "environment": environment, "limit": limit}
    body = {k: v for k, v in body.items() if v is not None}
    res = await _request("POST", f"/project/{project_id}/tasks", query=None, body=body)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='stop_task', readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=False))
async def stop_task(project_id: int, task_id: int) -> str:
    """POST /project/{project_id}/tasks/{task_id}/stop"""
    body = {"project_id": project_id, "id": task_id}
    body = {k: v for k, v in body.items() if v is not None}
    res = await _request("POST", f"/project/{project_id}/tasks/{task_id}/stop", query=None, body=body)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='create_template', readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=False))
async def create_template(project_id: int, name: str, playbook: str, inventory_id: int, repository_id: int, environment_id: int, app: str = "ansible", git_branch: Optional[str] = None, description: Optional[str] = None) -> str:
    """POST /project/{project_id}/templates"""
    body = {"project_id": project_id, "name": name, "playbook": playbook, "inventory_id": inventory_id, "repository_id": repository_id, "environment_id": environment_id, "app": app, "git_branch": git_branch, "description": description}
    body = {k: v for k, v in body.items() if v is not None}
    res = await _request("POST", f"/project/{project_id}/templates", query=None, body=body)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='update_template', readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=False))
async def update_template(project_id: int, template_id: int, name: str, playbook: str, inventory_id: int, repository_id: int, environment_id: int, app: str = "ansible", git_branch: Optional[str] = None, description: Optional[str] = None) -> str:
    """PUT /project/{project_id}/templates/{template_id}"""
    body = {"project_id": project_id, "id": template_id, "name": name, "playbook": playbook, "inventory_id": inventory_id, "repository_id": repository_id, "environment_id": environment_id, "app": app, "git_branch": git_branch, "description": description}
    body = {k: v for k, v in body.items() if v is not None}
    res = await _request("PUT", f"/project/{project_id}/templates/{template_id}", query=None, body=body)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='create_environment', readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=False))
async def create_environment(project_id: int, name: str, json_vars: str = "{}", env_vars: str = "{}", password: Optional[str] = None) -> str:
    """POST /project/{project_id}/environment"""
    body = {"project_id": project_id, "name": name, "json": json_vars, "env": env_vars, "password": password}
    body = {k: v for k, v in body.items() if v is not None}
    res = await _request("POST", f"/project/{project_id}/environment", query=None, body=body)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='update_environment', readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=False))
async def update_environment(project_id: int, environment_id: int, name: str, json_vars: str = "{}", env_vars: str = "{}", password: Optional[str] = None) -> str:
    """PUT /project/{project_id}/environment/{environment_id}"""
    body = {"project_id": project_id, "id": environment_id, "name": name, "json": json_vars, "env": env_vars, "password": password}
    body = {k: v for k, v in body.items() if v is not None}
    res = await _request("PUT", f"/project/{project_id}/environment/{environment_id}", query=None, body=body)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='create_inventory', readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=False))
async def create_inventory(project_id: int, name: str, inventory: str, type: str = "static", ssh_key_id: Optional[int] = None, become_key_id: Optional[int] = None, repository_id: Optional[int] = None) -> str:
    """POST /project/{project_id}/inventory"""
    body = {"project_id": project_id, "name": name, "inventory": inventory, "type": type, "ssh_key_id": ssh_key_id, "become_key_id": become_key_id, "repository_id": repository_id}
    body = {k: v for k, v in body.items() if v is not None}
    res = await _request("POST", f"/project/{project_id}/inventory", query=None, body=body)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='update_inventory', readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=False))
async def update_inventory(project_id: int, inventory_id: int, name: str, inventory: str, type: str = "static", ssh_key_id: Optional[int] = None, become_key_id: Optional[int] = None, repository_id: Optional[int] = None) -> str:
    """PUT /project/{project_id}/inventory/{inventory_id}"""
    body = {"project_id": project_id, "id": inventory_id, "name": name, "inventory": inventory, "type": type, "ssh_key_id": ssh_key_id, "become_key_id": become_key_id, "repository_id": repository_id}
    body = {k: v for k, v in body.items() if v is not None}
    res = await _request("PUT", f"/project/{project_id}/inventory/{inventory_id}", query=None, body=body)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='delete_template', readOnlyHint=False, destructiveHint=True, idempotentHint=True, openWorldHint=False))
async def delete_template(project_id: int, template_id: int, confirm: bool = False) -> str:
    """DELETE /project/{project_id}/templates/{template_id}"""
    if not confirm:
        return json.dumps({"error": "destructive operation refused", "tool": 'delete_template', "hint": "re-invoke with confirm=true to proceed"}, indent=2)
    res = await _request("DELETE", f"/project/{project_id}/templates/{template_id}", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='delete_environment', readOnlyHint=False, destructiveHint=True, idempotentHint=True, openWorldHint=False))
async def delete_environment(project_id: int, environment_id: int, confirm: bool = False) -> str:
    """DELETE /project/{project_id}/environment/{environment_id}"""
    if not confirm:
        return json.dumps({"error": "destructive operation refused", "tool": 'delete_environment', "hint": "re-invoke with confirm=true to proceed"}, indent=2)
    res = await _request("DELETE", f"/project/{project_id}/environment/{environment_id}", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='delete_inventory', readOnlyHint=False, destructiveHint=True, idempotentHint=True, openWorldHint=False))
async def delete_inventory(project_id: int, inventory_id: int, confirm: bool = False) -> str:
    """DELETE /project/{project_id}/inventory/{inventory_id}"""
    if not confirm:
        return json.dumps({"error": "destructive operation refused", "tool": 'delete_inventory', "hint": "re-invoke with confirm=true to proceed"}, indent=2)
    res = await _request("DELETE", f"/project/{project_id}/inventory/{inventory_id}", query=None, body=None)
    return json.dumps(res, indent=2, default=str)

@mcp.tool(annotations=ToolAnnotations(title='delete_task', readOnlyHint=False, destructiveHint=True, idempotentHint=True, openWorldHint=False))
async def delete_task(project_id: int, task_id: int, confirm: bool = False) -> str:
    """DELETE /project/{project_id}/tasks/{task_id}"""
    if not confirm:
        return json.dumps({"error": "destructive operation refused", "tool": 'delete_task', "hint": "re-invoke with confirm=true to proceed"}, indent=2)
    res = await _request("DELETE", f"/project/{project_id}/tasks/{task_id}", query=None, body=None)
    return json.dumps(res, indent=2, default=str)


def _list():
    tools = asyncio.run(mcp.list_tools())
    for t in tools:
        a = t.annotations
        ro = getattr(a, "readOnlyHint", None) if a else None
        de = getattr(a, "destructiveHint", None) if a else None
        print(f"{t.name:20} readOnly={ro} destructive={de}  {t.description}")
    print(f"\n{len(tools)} tools exposed "
          "(11 read / 8 write / 4 delete-guarded)")


if __name__ == "__main__":
    if "--list" in sys.argv:
        _list()
    else:
        mcp.run()
